Add files via upload

diff --git a/bincheck b/bincheck
--- a/bincheck
+++ b/bincheck
@@ -6,12 +6,14 @@ debug=false
 GREEN='\e[92m'
 RED='\e[91m'
 GRAY='\e[37m'
+PURPLE='\e[95m'
+CYAN='\e[96m'
 RESET='\e[39m'
 
 # Script starts below
 
 filecount=0
-errorcount=0 # number of checksum errors
+errorcount=0 # global number of checksum errors
 
 debugmessage() { [[ $debug == true ]] && echo -e "${GRAY}$1${RESET}"; }
 
@@ -26,14 +28,19 @@ hashcheck() {
     return
   fi
 
-  echo "'$1'"
+  errorcount_local=0 # number of current bin files' checksum errors
+
+  echo -e "Looking into ${PURPLE}$1${RESET}"
   checksums="" # list of known checksums the current .exe provides
   crcstring=$(strings "$1" | grep -i '#GOGCRCSTRING') # extract GOGCRCSTRING from .exe
   [[ $crcstring == "" ]] && { debugmessage "No checksums found in '$1'"; return; }
   crcstring=${crcstring%#GOGCRCSTRING*} # remove the string name, leaving numbers
   debugmessage "Raw GOGCRCSTRING: $crcstring"
   multiplier=${crcstring: -2} # the 2-digit number before '#GOGCRCSTRING'
-  debugmessage "Number of MD5 hashes: $multiplier"
+
+  echo -n "Found $((multiplier)) checksum"
+  if [[ $multiplier == "01" ]]; then echo ":"; else echo "s:"; fi
+
   crcstring=${crcstring::-2} # remove the 2-digit number
   md5hashes=${crcstring:(( - 10#$multiplier * 32 ))} # omit characters not part of the hashes
   md5hashes=${md5hashes,,} # set md5 hashes to lowercase
@@ -42,23 +49,36 @@ hashcheck() {
   for i in $(seq -w 01 "$multiplier"); do
     checksum=${md5hashes:(( 32 * ((10#$i - 1)) )):32}
     [[ "$checksum" == "" ]] && checksum="[empty]                         "
-    echo "$checksum"
+    echo -e "  - ${CYAN}$checksum${RESET}"
     checksums+=" $checksum" # add current checksum to known checksums
   done
 
+  echo "Verifying bin files:"
   for bin in "${1%.exe}"-*.bin; do
-    [[ -f $bin ]] || { debugmessage "BIN file(s) not found: '$bin'"; continue; }
+    [[ -f $bin ]] || {
+      echo "  ${RED}BIN file(s) not found: ${PURPLE}'$bin'${RESET}";
+      ((errorcount_local++))
+      continue;
+    }
     ((filecount++))
     filename=${bin##*/}
+    echo -en "  - ${PURPLE}$filename${RESET} "
     result=$(md5sum "$bin")
     checksum=${result%  *}
     if [[ "$checksums" == *"$checksum"* ]] # is checksum known?
-    then echo -e "${GREEN}$checksum OK${RESET} $filename"
+    then echo -e "${CYAN}$checksum ${GREEN}OK${RESET}"
     else
-      echo -e "${RED}$checksum CHECKSUM ERROR${RESET} $filename"
+      echo -e "${RED}$checksum ERROR${RESET}"
       ((errorcount++))
+      ((errorcount_local++))
     fi
   done
+
+  if [[ errorcount_local -gt 0 ]]; then
+    echo -e "Encountered ${RED}$errorcount_local errors${RESET}!"
+  else
+    echo -e "Done."
+  fi
   echo
 }
 
@@ -93,6 +113,10 @@ while [[ "$1" != "" ]]; do
 done
 
 echo -n "$filecount bin file(s), "
-[[ "$errorcount" -gt 0 ]] && echo -en "${RED}"
-echo "$errorcount checksum errors"
+if [[ "$errorcount" -gt 0 ]]; then
+  echo -en "${RED}"
+else
+  echo -en "${GREEN}"
+fi
+echo -n "$errorcount checksum error(s)"
 exit "$errorcount"
