Add files via upload

diff --git a/bincheck b/bincheck
--- a/bincheck
+++ b/bincheck
@@ -1,84 +1,74 @@
 #!/bin/bash
 
-# User settings
+# User variables
 
 debug=false
-GREEN='\e[92m'
-RED='\e[91m'
-GRAY='\e[37m'
-PURPLE='\e[95m'
-CYAN='\e[96m'
-RESET='\e[39m'
+
+color_success='\e[92m'
+color_error='\e[91m'
+color_file='\e[95m'
+color_debug='\e[90m'
+color_reset='\e[39m'
 
 # Script starts below
 
 filecount=0
 errorcount=0 # global number of checksum errors
+errorfiles=""
 
-debugmessage() { [[ $debug == true ]] && echo -e "${GRAY}$1${RESET}"; }
+debugmessage() { [[ $debug == true ]] && echo -e "${color_debug}$1${color_reset}"; }
 
 # this function accepts .exe files
 hashcheck() {
   # skip should the .exe be a directory (for whatever reason)
-  [[ -d "$1" ]] && { debugmessage "Skipped directory '$1'"; return; }
+  [[ -d $1 ]] && { debugmessage "Skipped directory '$1'"; return; }
   # skip when no .bin files exist
   ls "${1%.exe}"-*.bin &> /dev/null
-  if [[ "$?" != 0 ]]; then
-    debugmessage "No BIN files found for '$1'"
+  if [[ $? != 0 ]]; then
+    debugmessage "No bin files found for '$1'"
     return
   fi
 
-  errorcount_local=0 # number of current bin files' checksum errors
-
-  echo -e "Looking into ${PURPLE}$1${RESET}"
+  echo -e "Looking into ${color_file}$1${color_reset} ..."
   checksums="" # list of known checksums the current .exe provides
   crcstring=$(strings "$1" | grep -i '#GOGCRCSTRING') # extract GOGCRCSTRING from .exe
   [[ $crcstring == "" ]] && { debugmessage "No checksums found in '$1'"; return; }
   crcstring=${crcstring%#GOGCRCSTRING*} # remove the string name, leaving numbers
   debugmessage "Raw GOGCRCSTRING: $crcstring"
   multiplier=${crcstring: -2} # the 2-digit number before '#GOGCRCSTRING'
-
-  echo -n "Found $((multiplier)) checksum"
-  if [[ $multiplier == "01" ]]; then echo ":"; else echo "s:"; fi
-
   crcstring=${crcstring::-2} # remove the 2-digit number
   md5hashes=${crcstring:(( - 10#$multiplier * 32 ))} # omit characters not part of the hashes
   md5hashes=${md5hashes,,} # set md5 hashes to lowercase
   debugmessage "Raw MD5 hashes: $md5hashes"
+  echo -n "Found $((multiplier)) checksum"
+  if [[ $multiplier == "01" ]]; then echo ":"; else echo "s:"; fi
 
   for i in $(seq -w 01 "$multiplier"); do
     checksum=${md5hashes:(( 32 * ((10#$i - 1)) )):32}
-    [[ "$checksum" == "" ]] && checksum="[empty]                         "
-    echo -e "  - ${CYAN}$checksum${RESET}"
+    [[ $checksum == "" ]] && checksum="[empty]                         "
+    echo "   $checksum"
     checksums+=" $checksum" # add current checksum to known checksums
   done
 
-  echo "Verifying bin files:"
   for bin in "${1%.exe}"-*.bin; do
     [[ -f $bin ]] || {
-      echo "  ${RED}BIN file(s) not found: ${PURPLE}'$bin'${RESET}";
-      ((errorcount_local++))
+      echo "Bin file(s) not found: ${color_error}'$bin'${color_reset}";
       continue;
     }
     ((filecount++))
     filename=${bin##*/}
-    echo -en "  - ${PURPLE}$filename${RESET} "
+    echo "Verifying $filename ..."
     result=$(md5sum "$bin")
     checksum=${result%  *}
-    if [[ "$checksums" == *"$checksum"* ]] # is checksum known?
-    then echo -e "${CYAN}$checksum ${GREEN}OK${RESET}"
+    if [[ $checksums == *"$checksum"* ]] # is checksum known?
+    then echo -e "-> $checksum ${color_success}OK${color_reset}"
     else
-      echo -e "${RED}$checksum ERROR${RESET}"
+      echo -e "-> $checksum ${color_error}ERROR${color_reset}"
       ((errorcount++))
-      ((errorcount_local++))
+      errorfiles+="$filename
+"
     fi
   done
-
-  if [[ errorcount_local -gt 0 ]]; then
-    echo -e "Encountered ${RED}$errorcount_local errors${RESET}!"
-  else
-    echo -e "Done."
-  fi
   echo
 }
 
@@ -92,7 +82,7 @@ while [[ "$1" != "" ]]; do
 
     # skip directories without .exe files
     ls "$1"/*.exe &> /dev/null
-    if [[ "$?" != 0 ]]; then
+    if [[ $? != 0 ]]; then
       debugmessage "Skipped directory without EXE files: '$1'"
       shift
       continue
@@ -104,7 +94,7 @@ while [[ "$1" != "" ]]; do
 
   # for other arguments, skip those that are not .exe files
   elif [[ -f "$1" ]]; then
-    if [[ "${1: -4}" == ".exe" ]]; then hashcheck "$1"
+    if [[ ${1: -4} == ".exe" ]]; then hashcheck "$1"
     else debugmessage "Skipped non-EXE file: '$1'"
     fi
   fi
@@ -113,10 +103,11 @@ while [[ "$1" != "" ]]; do
 done
 
 echo -n "$filecount bin file(s), "
-if [[ "$errorcount" -gt 0 ]]; then
-  echo -en "${RED}"
+if [[ $errorcount -gt 0 ]]; then
+  echo -en "${color_error}"
 else
-  echo -en "${GREEN}"
+  echo -en "${color_success}"
 fi
 echo "$errorcount checksum error(s)"
+if [[ $errorcount -gt 0 ]]; then echo "$errorfiles"; fi
 exit "$errorcount"
diff --git a/innocheck b/innocheck
--- a/innocheck
+++ b/innocheck
@@ -3,22 +3,24 @@
 filecount=0
 errorcount=0
 errorfiles=""
+red='\e[91m'
+green='\e[92m'
+purple='\e[95m'
+reset='\e[39m'
 
 [[ "$1" == "" ]] && set -- .
 
 function inno {
   innoerror=false
   ((filecount++))
-  innoextract --test --list-checksums "$1"
-  [[ "$?" != "0" ]] && innoerror=true
-  innoextract --test --no-gog-galaxy --list-checksums "$1"
-  [[ "$?" != "0" ]] && innoerror=true
-  if [[ "$innoerror" == true ]]; then
+  echo -e "Testing ${purple}$1${reset}"
+  innoextract --gog --test --silent --progress=1 "$1"
+  if [[ "$?" != "0" ]]; then
     ((errorcount++))
     errorfiles+="$1
 "
+    echo -e "  ${red}Encountered errors${reset}."
   fi
-  echo
 }
 
 while [[ "$1" != "" ]]; do
@@ -27,11 +29,11 @@ while [[ "$1" != "" ]]; do
   shift
 done
 
-echo "$filecount exe file(s), $errorcount errors"
-if [[ "$errorcount" -gt 0 ]]; then
-  echo Press RETURN to see error files
-  read
-  echo
-  echo "$errorfiles"
+echo -n "$filecount exe file(s), "
+if [[ $errorcount == 0 ]]; then echo -en "${green}"; else echo -en "${red}"; fi
+echo -e "$errorcount error(s)${reset}"
+if [[ $errorcount -gt 0 ]]; then
+  echo "Listing files with errors:"
+  echo -e "${red}$errorfiles${reset}"
 fi
 exit "$errorcount"
