Fixed a bug that happened when using Git BASH
- When using Git BASH, the checksums are now correctly compared.
- The script now checks for the "file" command.
- Updated strings.

diff --git a/gogcheck b/gogcheck
--- a/gogcheck
+++ b/gogcheck
@@ -37,17 +37,23 @@ subjects="
 /C=PL/L=Warszawa/O=GOG Sp. z o.o./CN=GOG Sp. z o.o.
 /C=CY/L=Larnaca/O=GOG Limited/CN=GOG Limited
 /C=CY/L=Nicosia/O=GOG Limited/CN=GOG Limited
+/C=PL/ST=Mazowieckie/L=Warszawa/O=GOG Sp. z o.o./CN=GOG Sp. z o.o.
 
 /C=US/O=DigiCert/CN=DigiCert Timestamp Responder
 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Code Signing CA-1
 /C=US/O=DigiCert, Inc./CN=DigiCert Timestamp 2021
+/C=US/O=DigiCert/CN=DigiCert Timestamp 2022 - 2
 "
 
 issuers="
 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Assured ID Code Signing CA
 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID CA-1
-/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Assured ID Timestamping CA"
+/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Assured ID Timestamping CA
+/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4
+/C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
+/C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA
+"
 
 serials="
 06F56DD38538018E9A31248796E640AB
@@ -57,6 +63,7 @@ serials="
 05B5D9D6BB2960FBD330C5D6B9B7B7D2
 087DE552D352D9BAF0C2B6DF6AC4C64A
 096DCF2E35C66F13EF95FCC8BFAC3E11
+0B17A63F5D10CB7D3B78AF8F676C7667
 
 0409181B5FD5BB66755343B56F955008
 03019A023AFF58B16BD6D5EAE617F066
@@ -66,6 +73,10 @@ serials="
 039FEDEDCB795B8DED320C8919F03689
 0D424AE0BE3A88FF604021CE1400F0DD
 0AA125D6D6321B7E41E405DA3697C215
+0E9B188EF9D02DE7EFDB50E20840185A
+073637B724547CD847ACFD28662A5E5B
+08AD40B260D29C4C9F5ECDA9BD93AED9
+0C4D69724B94FA3C2A4A3D2907803D5A
 "
 
 set_colors() {
@@ -170,6 +181,13 @@ fi
   echo "Download the latest version from https://constexpr.org/innoextract."
   exit 1
 }
+
+# Check for "file" command
+if ! file -v &> /dev/null; then
+  echo "The \"file\" command is not available on this system. RAR files cannot be detected and will produce errors during the innoextract check."
+else
+  file_command_available=1
+fi
 
 # Disable unrar if not available
 if [[ ! -z ${unraroption+x} && $check_innosetup == true \
@@ -328,7 +346,7 @@ bincheck() {
     if [[ $disable_binchecksumcalculation != true ]]; then
       echo "${bin##*/}: "
       checksum=$(md5sum "$bin")
-      checksum=${checksum%  *}
+      checksum=${checksum%% *}
       echo -n "$checksum: "
       if [[ $checksums == *"$checksum"* ]]; then
         echo -e "${color_success}OK${color_reset}"
@@ -379,7 +397,7 @@ innocheck() {
   fi
 
   # Detect RAR archives
-  if [[ -f "${1%.exe}"-1.bin ]]; then
+  if [[ $file_command_available && -f "${1%.exe}"-1.bin ]]; then
     if [[ $(file "${1%.exe}"-1.bin) == *RAR* ]]; then
       echo -e "${color_unknown}RAR format detected.${color_reset} Innoextract does not know bin contents' checksums."
       if [[ $disable_extracting != true && $unraroption != '--gog' ]]; then
