Add files via upload

diff --git a/innocheck b/innocheck
--- a/innocheck
+++ b/innocheck
@@ -2,48 +2,49 @@
 
 # User variables
 
-silent=true
+verbose=true
 
-color_error='\e[91m'
-color_success='\e[92m'
+color_error='\e[91m\e[1m'
+color_success='\e[92m\e[1m'
 color_file='\e[95m'
-color_reset='\e[39m'
+color_reset='\e[39m\e[0m'
 
 # Script starts below
 
 filecount=0
 errorcount=0
 errorfiles=""
-if [[ $silent == true ]]; then
-  silent="--silent"
+if [[ $verbose == true ]]; then
+  verbose="--list-checksums"
 else
-  silent=""
+  verbose=""
 fi
 
-[[ "$1" == "" ]] && set -- . # if no arguments given, use current directory
+[[ $1 == "" ]] && set -- . # if no arguments given, use current directory
 
 inno() {
   innoerror=false
   ((filecount++))
-  echo -e "Testing ${color_file}$1${color_reset}"
+  echo -e "Extract-testing ${color_file}$1${color_reset}"
+  innoextract --test --silent $verbose --progress=1 "$1"
+  if [[ $? != 0 ]]; then innoerror=true; fi
 
   # show info why RAR archives are skipped
   if [[ -f "${1%.exe}"-1.bin ]]; then
     if [[ $(file "${1%.exe}"-1.bin) == *RAR* ]]; then
-      echo "The bin file(s) for this particular game are in RAR format and not part of Inno Setup. The content's checksums are not known. You can ignore the following innoextract warnings."
+      echo "SCRIPT MESSAGE: The bin file(s) for this particular game are in RAR format and not part of Inno Setup. The content's checksums are not known, so testing bin files has been skipped on purpose. You can ignore innoextract messages in this regard."
     fi
   fi
 
-  innoextract --test $silent --progress=1 "$1"
-  if [[ "$?" != "0" ]]; then
+  if [[ $innoerror == true ]]; then
     ((errorcount++))
     errorfiles+="$1
 "
-    echo -e "  ${color_error}Encountered errors${color_reset}."
+    echo -e "${color_error}Encountered errors!${color_reset}"
   fi
 }
 
-while [[ "$1" != "" ]]; do
+while [[ $1 != "" ]]; do
   [[ -d "$1" ]] && for exe in "$1"/*.exe; do [[ -f "$exe" ]] && inno "$exe"; done
   [[ -f "$1" ]] && inno "$1"
   shift
@@ -51,7 +52,7 @@ done
 
 echo
 echo -n "$filecount exe file(s), "
-if [[ $errorcount == 0 ]]; then 
+if [[ $errorcount == 0 ]]; then
   echo -en "${color_success}"
 else
   echo -en "${color_error}"
diff --git a/sigcheck b/sigcheck
--- a/sigcheck
+++ b/sigcheck
@@ -41,10 +41,10 @@ COLOR_KNOWN='02;32'
 COLOR_OK='01;32'
 COLOR_ERROR='01;91'
 
-color_red='\e[91m'
-color_green='\e[92m'
+color_error='\e[91m\e[1m'
+color_success='\e[92m\e[1m'
 color_file='\e[95m'
-color_reset='\e[39m'
+color_reset='\e[39m\e[0m'
 
 # Script starts below
 
@@ -65,8 +65,9 @@ Failed
 
 filecount=0
 errorcount=0
+errorfiles=""
 
-[[ "$1" == "" ]] && set -- . # if no arguments given, use current directory
+[[ $1 == "" ]] && set -- . # if no arguments given, use current directory
 
 sigcheck() {
   echo -e "Verifying ${color_file}$1${color_reset}"
@@ -77,12 +78,16 @@ sigcheck() {
     grep --color=always -e "$serials $subjects $issuers" | \
     GREP_COLOR=$COLOR_ERROR \
     grep --color=always -e "$errorstrings"
-  [[ "${PIPESTATUS[0]}" != 0 ]] && ((errorcount++))
+  if [[ ${PIPESTATUS[0]} != 0 ]]; then
+    ((errorcount++))
+    errorfiles+="$1
+"
+  fi
   ((filecount++))
   echo
 }
 
-while [[ "$1" != "" ]]; do
+while [[ $1 != "" ]]; do
 
   if [[ -d "$1" ]]; then
     for exe in "$1"/*.exe; do
@@ -91,16 +96,16 @@ while [[ "$1" != "" ]]; do
     done
   fi
 
-  [[ -f "$1" ]] && [[ "$1" == *.exe ]] && sigcheck "$1"
+  [[ -f "$1" ]] && [[ $1 == *.exe ]] && sigcheck "$1"
 
   shift
 done
 
 echo -n "$filecount file(s), "
 if [[ $errorcount == 0 ]]; then
-  echo -en "${color_green}"
+  echo -en "${color_success}"
 else
-  echo -en "${color_red}"
+  echo -en "${color_error}"
 fi
 echo -e "$errorcount error(s)${color_reset}"
 if [[ $errorcount -gt 0 ]]; then
